### ISSUE TITLE
NPC: Kafra Shop

### ISSUE THREAD

**Issue by ckx** [ckx/roguenarok#10]
Make a custom shop that has random rewards.

Assigning to both of us because I dunno who will be doing this.

This issue can be closed when the Kafra exists, with a jRO Kafra portrait, and sells a static stock of consumables + random stock of gear.

**Comment by Pienne** [comment]
https://www.github.com/ckx/roguenarok/commit/59a73045
done for now as a skeleton draft for things we will likely do later.

notes:
- rerolls some items on event called by npc #2
- currently uses npc scope (.shopstring$ for example) but we will likely need to adjust this for other applications

food for thought:
- can be further simplified to use only default pricing (getiteminfo)
- getiteminfo can also be used to operate on an array of aegisnames as well

**Comment by Pienne** [comment]
rip, still need to do OnBuyItem and OnSellItem. will close again when it is implemented + working properly (includes handling zeny and weight cases)

**Comment by Pienne** [comment]
done! trades now resolve.
I also added a check to the shop contents since it was bypassing the server's normal check for infinite zeny loops.

zeny and weight checks are handled by client, so it's fine not to check for weight server-side, but I kept code from the dynamic shop template that ensures people aren't doing weird things like buying or selling negative amounts of items, or buying/selling more than they should be able to.
