### ISSUE TITLE
Change equip swap cooldown to 0

### ISSUE THREAD

**Issue by Pienne** [ckx/roguenarok#37]
your judgement @ckx but 10s is overkill and having a single key to swap weapons+armor is kinda nice, all of it at once is kinda OP though.

it's also a good workaround for the finicky dual wielding stuff that goes on now that every class can theoretically do that.

i'm happy to figure out where it is and make the change, also

**Comment by ckx** [comment]
This is my first exposure to the equipment swap system—My first instinct upon seeing it was to disable it, but I didn't know about the cooldown.

I'm inclined to go in the other direction than you and raise the cooldown rather than lower it. I think removing it outright is a bad idea. Here are some things I worry about if we lower the cooldown:

1. It trivializes changing between a full reduction set and a full damage set. This puts survivability through the roof for most builds that are typically high risk/high reward.
   * MATK is calculated when a skill hits, so casters will only have to wear their damage set right when a spell goes off.
1. It trivializes changing your damage _type_, say we have a dagger Rogue that can easily swap to a full bow set, the utility is simply too high.
1. Classic swaps are part of your "hotkey" build. Hotkeys are a limiter in RO—You have exactly 36 "things" you have easy access to. This sets it apart from other MMOs where you can do all sorts of crazy hotkey combinations and anything you get is available to you. Instead, choosing what you have easy access to is a conscious decision, and becomes a part of your overall build.
1. It reduces the skill required for managing your gear.

Point 4) is potentially contentious because managing your gear swaps in RO treads a fine line between skillful (e.g. smokie swaps) and tedious (e.g. phen swaps).

So, my inclinations is to either remove the gear swap system entirely, or keep it with a cooldown. If we keep it with a cooldown, I think it makes a nice emergency button for switching to full redux gear. 

After trying the feature out, you can still swap equipment one by one with the classic methods during the cooldown. This means you can have high-priority items still hotkey'd on your bar, but use the full gear swap button occasionally when you _really_ need it. To me a 30 second cooldown sounds good, but I'd be happy to leave it at 10 seconds and tweak it in playtesting.

**Comment by Pienne** [comment]
that sounds really fair and interesting, yeah. particularly if you don't need to have the items on your hotkey bar to swap to them.
sounds like we're good keeping it with a cooldown at the moment so i'm closing for now, we can make another issue for adjusting the time later and reference this one.
